name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        minecraft_version: ['1.21']
        include:
          - minecraft_version: '1.21'
            neo_version: '21.0.166'
            parchment_version: '2024.07.28'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-cleanup: on-success

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Make Gradle wrapper executable
        run: chmod +x ./TravelersGarden/NeoForge/gradlew

      - name: Clean Gradle cache
        run: |
          cd ./TravelersGarden/NeoForge
          ./gradlew clean --refresh-dependencies

      - name: Update gradle.properties for current Minecraft version
        run: |
          cd ./TravelersGarden/NeoForge
          sed -i "s/minecraft_version=.*/minecraft_version=${{ matrix.minecraft_version }}/" gradle.properties
          sed -i "s/minecraft_version_range=.*/minecraft_version_range=[${{ matrix.minecraft_version }}]/" gradle.properties
          sed -i "s/neo_version=.*/neo_version=${{ matrix.neo_version }}/" gradle.properties
          sed -i "s/neo_version_range=.*/neo_version_range=[${{ matrix.neo_version }},)/" gradle.properties
          sed -i "s/neogradle.subsystems.parchment.minecraftVersion=.*/neogradle.subsystems.parchment.minecraftVersion=${{ matrix.minecraft_version }}/" gradle.properties
          sed -i "s/neogradle.subsystems.parchment.mappingsVersion=.*/neogradle.subsystems.parchment.mappingsVersion=${{ matrix.parchment_version }}/" gradle.properties
          sed -i "s/mod_version=.*/mod_version=${{ steps.version.outputs.VERSION }}-mc${{ matrix.minecraft_version }}/" gradle.properties

      - name: Validate NeoForge version availability
        run: |
          echo "Validating NeoForge version ${{ matrix.neo_version }} for Minecraft ${{ matrix.minecraft_version }}..."
          cd ./TravelersGarden/NeoForge
          echo "Checking available repositories..."
          ./gradlew dependencies --configuration implementation --dry-run
          echo "Attempting to resolve NeoForge dependency..."
          ./gradlew dependencies --configuration implementation | grep "net.neoforged:neoforge" || {
            echo "ERROR: NeoForge version ${{ matrix.neo_version }} not found!"
            echo "Available versions can be checked at: https://projects.neoforged.net/neoforged/neoforge"
            exit 1
          }

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./TravelersGarden/NeoForge

      - name: Find JAR file
        id: jar
        run: |
          JAR_FILE=$(find ./TravelersGarden/NeoForge/build/libs -name "*.jar" | grep -v sources | head -1)
          echo "JAR_PATH=$JAR_FILE" >> $GITHUB_OUTPUT
          echo "JAR_NAME=$(basename $JAR_FILE)" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: travelersgarden-${{ steps.version.outputs.VERSION }}-mc1.21-universal
          path: ${{ steps.jar.outputs.JAR_PATH }}

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release v${{ steps.version.outputs.VERSION }}
          body: |
            ## Travelers Garden v${{ steps.version.outputs.VERSION }}
            
            ### Features
            - Portable gardening while on the move
            - Works underground, in the Nether, and End dimensions
            - Slower growth rate for balance
            
            ### Compatibility
            This release supports:
            - **Minecraft 1.21.x** (including 1.21, 1.21.1, 1.21.2, etc.)
            - Built with NeoForge ${{ matrix.neo_version }}
            
            ### Installation
            1. Download the JAR file below
            2. Place it in your mods folder
            3. Make sure you have NeoForge installed for Minecraft 1.21.x
            
            ### Files
            - `travelersgarden-${{ steps.version.outputs.VERSION }}-mc1.21.jar` - Compatible with all Minecraft 1.21.x versions
          files: ./artifacts/**/*.jar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
